[BR-13]: method create workspace
ignavan39/broker pull request #14
Opened 2022-06-15 16:21 UTC by enmex

2022-06-15 18:58 UTC, ignavan39 requested changes

2022-06-15 18:58 UTC, ignavan39 commented on app/delivery/http/workspace/v1/controller.go
> +			httpext.AbortJSON(w, err.Error(), http.StatusNotFound)
Return забыл

2022-06-15 18:58 UTC, ignavan39 commented on app/dto/workspace.go
> +	Name      *string `json:"name"`
А почему имя указатель когда она обязательное ?

2022-06-15 18:58 UTC, ignavan39 commented on app/dto/workspace.go
> +	Name      *string   `json:"name"`
Здесь тоже

2022-06-15 18:58 UTC, ignavan39 commented on app/repository/workspace/repo.go
> +		PlaceholderFormat(sq.Dollar).Exec()
Exec перенеси на след строку

2022-06-15 18:58 UTC, ignavan39 commented on app/repository/workspace/repo.go
> +	if err := row.Scan(&workspace.Id, &workspace.Name, &workspace.CreatedAt, &workspace.IsPrivate); err != nil {
А там разве есть какой то юник на воркспейс?

2022-06-15 19:02 UTC, ignavan39 commented on app/repository/workspace/repo.go
> +		if duplicate {
Я про эту строчку

2022-06-15 19:13 UTC, ignavan39 commented on app/service/errors.go
> +	PasswordNotMatch           = errors.New("password doesn't match")
Раз там все с большой буквы сделай тут тоже
password -> Password

2022-06-15 21:11 UTC, enmex commented on app/repository/workspace/repo.go
> +		if duplicate {
дупликат по имени

2022-06-15 21:15 UTC, enmex commented on app/repository/workspace/repo.go
> +		if duplicate {
хотя ладно, может быть хоть сколько воркспейсов с одинаковым именем, ща подумал вот

2022-06-16 02:41 UTC, ignavan39 commented on app/repository/workspace/repo.go
> +		if duplicate {
Это у workspace_accesses, чтобы инвайт нельзя было несколько раз кинуть
Я про просто workspace
Ну наверное да, либо оставить как есть
Либо добавить author_id в workspace
И сделать юник по (name, author_id)

2022-06-16 04:58 UTC, ignavan39 approved these changes

2022-06-16 05:02 UTC, merged