[FEAT][BR-22][DRAFT]: added invites
ignavan39/broker pull request #26
Opened 2022-06-24 12:03 UTC by enmex

2022-06-24 12:15 UTC, ignavan39 commented on app/delivery/http/invitation/v1/controller.go
> +	ctx := r.Context()
в 28 стр перенеси

2022-06-24 12:15 UTC, ignavan39 commented on app/delivery/http/invitation/v1/controller.go
> +	if err != nil {
в одну стр

```go
if err; err := json.NewDecoder(r.Body).Decode(&payload)
```

2022-06-24 12:15 UTC, ignavan39 commented on app/delivery/http/invitation/v1/router.go
> +			r.Post("/{workspaceID}", rt.controller.SendInvitation)
`create` prefix

2022-06-24 12:15 UTC, ignavan39 commented on app/repository/user/repo.go
> +	blogger.Println("update")
это нужно ?

2022-06-24 12:15 UTC, ignavan39 commented on app/repository/user/repo.go
> +	blogger.Println("Before loop")
тот же вопрос

2022-06-25 05:25 UTC, ignavan39 requested changes

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/user/repo.go
> +		RunWith(r.pool.Write()).
RunWith (tx)

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/user/repo.go
> +			RunWith(r.pool.Write()).
Аналогично

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/user/repo.go
> +				return service.DuplicateWorkspaceAccessErr
Закомммить забыл, это может плохо кончится

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/workspace/repo.go
>  			return nil, service.DuplicateWorkspaceErr
Закомммить

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/workspace/repo.go
>  		Values(name, isPrivate).
RunWith не от транзакции

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/workspace/repo.go
>  		PlaceholderFormat(sq.Dollar).
RunWith не от транзакции

2022-06-25 05:25 UTC, ignavan39 commented on app/repository/workspace/repo.go
>  			return nil, service.DuplicateWorkspaceEmailErr
Закомммить

2022-06-25 07:00 UTC, ignavan39 commented on app/repository/workspace/repo.go
>  			return nil, service.DuplicateWorkspaceEmailErr
Можно через defer

https://go.dev/doc/database/execute-transactions

2022-06-26 03:15 UTC, ignavan39 requested changes

2022-06-26 03:15 UTC, ignavan39 commented on app/delivery/http/invitation/v1/router.go
> +			r.Delete("/{workspaceID}", rt.controller.CancelInvitation)
Post

2022-06-26 03:15 UTC, ignavan39 commented on app/delivery/http/invitation/v1/router.go
> +			r.Delete("/{workspaceID}", rt.controller.CancelInvitation)
Prefix `cancel`

2022-06-26 03:15 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
А как его может не быть ?

2022-06-26 03:15 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
Вопрос тот же

2022-06-26 03:15 UTC, ignavan39 commented on app/repository/user/repo.go
> +		Where(sq.Eq{"workspace_id": workspaceID, "sender_id": senderID, "ricipient_email": ricipientEmail}).
Тут не так, всё проще, я тебе просто айди инвайта пришлю, я ж их все могу получить и мне будет известен айди

2022-06-26 03:15 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
Тут просто айди и даже не так, это не нужно, я тебе в урл параметрах пришлю

2022-06-26 03:15 UTC, ignavan39 commented on app/delivery/http/invitation/v1/router.go
> +			r.Delete("/{workspaceID}", rt.controller.CancelInvitation)
suffix `:id`

2022-06-26 05:54 UTC, enmex commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
когда не выбрал имейлы и нажал отправить

2022-06-26 06:06 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
так это на фронте проблема, бек не должен знать что кто-то мог не выбрать емейл, такого запроса с точки зрения бека быть не может и тем более он отвалится на методе сериализации JSON'a

2022-06-26 06:36 UTC, enmex commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
в урл передать воркспейс и инвайт?

2022-06-26 06:40 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
Инвайт id

2022-06-26 06:46 UTC, enmex commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
вместо емейла передавать айди воркспейса?

2022-06-26 06:58 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
Да но не в дто, а в урл параметрах

2022-06-26 06:59 UTC, ignavan39 commented on app/delivery/http/invitation/v1/router.go
> +			r.Delete("/{workspaceID}", rt.controller.CancelInvitation)
```go
r.Post("cancel/:id")
```

2022-06-26 07:03 UTC, enmex commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
а айди инвайта как, я думал в в урл его надо передать. Итого у нас юзер и инвайт известен. Потом по ним просто отменяем инвайт, если он есть - если нет, то ошибка инвайт не найден

2022-06-28 07:22 UTC, ignavan39 requested changes

2022-06-28 07:22 UTC, ignavan39 commented on services/core/delivery/http/invitation/v1/controller.go
> +		httpext.AbortJSON(w, service.EmptyUrlParamsErr.Error(), http.StatusBadRequest)
return забыл

2022-06-28 07:22 UTC, ignavan39 commented on services/core/delivery/http/invitation/v1/controller.go
> +		httpext.AbortJSON(w, service.EmptyUrlParamsErr.Error(), http.StatusBadRequest)
return забыл

2022-06-28 07:22 UTC, ignavan39 commented on services/core/delivery/http/invitation/v1/controller.go
> +		httpext.AbortJSON(w, service.EmptyUrlParamsErr.Error(), http.StatusBadRequest)
аналогично

2022-06-28 07:22 UTC, ignavan39 commented on services/core/delivery/http/workspace/v1/controller.go
> +	blogger.Println(userId)
это нужно ?

2022-06-28 07:22 UTC, ignavan39 commented on services/core/dto/invitation.go
> +		return errors.New("Choose an email to send invitation")
в ошибках должна быть конкретная причина ошибки

"пустой емейл"

2022-06-28 07:22 UTC, ignavan39 commented on services/core/repository/user/repo.go
> +		Where(sq.Eq{"sender_id": senderID, "id": invitationID}).
не только sender может закрыть, может еще и админ

2022-06-28 07:50 UTC, enmex commented on services/core/repository/user/repo.go
> +		Where(sq.Eq{"sender_id": senderID, "id": invitationID}).
sender это либо модератор либо админ

2022-06-28 08:16 UTC, ignavan39 commented on services/core/repository/user/repo.go
> +		Where(sq.Eq{"sender_id": senderID, "id": invitationID}).
да, но его может отменить другой модератор, и тогда не найдется этот инвайт, тут просто по id

2022-06-28 10:57 UTC, ignavan39 commented on services/core/delivery/http/peer/v1/controller.go
> +		httpext.AbortJSON(w, fmt.Sprintf("failed decode payload %s", err.Error()), http.StatusBadRequest)
return

2022-06-29 04:36 UTC, ignavan39 commented on app/dto/invitation.go
> +	RicipientEmail *string `json:"ricipientEmail,omitempty"`
Так приджоини сендера и получишь юзера 
А recipient быть не может кстати я не видел но можно чекнуть что этого recipient ещё нет в рамках этого workspace

2022-06-29 04:49 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +	blogger.Println("HERE")
Это нужно?

2022-06-29 04:49 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +func (r *Repository) CheckInvites(userID string, email string) error {
Название функции не передаёт сути того что она делает

2022-06-29 04:49 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +func (r *Repository) CheckInvites(userID string, email string) error {
AcceptIntoWorkspace - что-то такое должно быть

2022-06-29 04:49 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +		OrderBy("created_at ASC").
DESC

2022-06-29 04:49 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +		OrderBy("created_at ASC").
И вторым параметром sender_id

2022-06-29 06:40 UTC, enmex commented on services/core/repository/invitation/repo.go
> +		OrderBy("created_at ASC").
а зачем по айди сортировать?

2022-06-29 09:07 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +	code := utils.CryptString(senderID+workspaceID, config.GetConfig().Invitation.InvitationHashSalt)
fmt.Sprintf

2022-06-29 09:07 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +		Where(sq.Eq{"code": code}).
а вот здесь кстати было бы резонно проверить что инвайт точно какого то определенного пользователя

т.е теоритически как сейчас это работает
некий админ кинул инвайт тебе, и если я какими либо образом его узнаю и стукнусь в апишку то отвалюсь только на том что у меня есть такой workspace_access

2022-06-29 09:07 UTC, ignavan39 commented on services/core/delivery/http/invitation/v1/router.go
> +			r.Post("/accept/{code}", rt.controller.AcceptInvitation)
что-то мне не сильно нравится идея передавать огромную строку в урле

2022-06-29 09:11 UTC, enmex commented on services/core/delivery/http/invitation/v1/router.go
> +			r.Post("/accept/{code}", rt.controller.AcceptInvitation)
в дто тогда?

2022-06-29 09:15 UTC, ignavan39 commented on services/core/delivery/http/invitation/v1/controller.go
> +	if err != nil {
не хэндлишь "нет прав"

2022-06-29 09:15 UTC, ignavan39 commented on services/core/dto/invitation.go
> +	if len(p.RicipientEmail) == 0 {
там еще isCorrectMail заюзай из auth помоему

2022-06-29 09:15 UTC, ignavan39 commented on services/core/repository/invitation/repo.go
> +		Values(senderID, ricipientEmail, workspaceID, code).
system_status = send

2022-06-29 09:15 UTC, ignavan39 commented on services/core/repository/peer/repo.go
> +		Where(sq.Eq{"wa.workspace_id": workspaceID}, sq.NotEq{"u.id": userID}).
почему not equal ?

2022-06-29 09:17 UTC, enmex commented on services/core/repository/invitation/repo.go
> +		Where(sq.Eq{"code": code}).
то есть проверить что приглашенный уже есть в воркспейсе?

2022-06-29 15:57 UTC, ignavan39 approved these changes

2022-06-29 15:57 UTC, merged