[FEAT]: email sending
ignavan39/broker pull request #44
Opened 2022-07-07 19:12 UTC by enmex

close #5 
close #40

2022-07-08 08:44 UTC, ignavan39 commented on services/smtp/server.go
> +func NewAPIServer(listenOn string) *Server {
С этим бы чото придумать потому что в core дублируется

2022-07-08 15:00 UTC, ignavan39 requested changes

2022-07-08 15:00 UTC, ignavan39 commented on services/smtp/sender/services/sender.go
> +	msg := "MIME-version: 1.0;\nContent-Type: text/html; charset=\"UTF-8\";\r\n"
Не плохо но если нужно будет аттачмент ?

2022-07-08 15:06 UTC, ignavan39 requested changes

2022-07-08 15:06 UTC, ignavan39 commented on services/core/.env.example
> +MAILGUN_PUBLIC_KEY=
Да можешь удалить это

2022-07-08 15:06 UTC, ignavan39 commented on services/smtp/.env.example
> +SENDER_GMAIL = "infbrokerinfo@gmail.com"
Оставь пустыми

2022-07-08 15:06 UTC, ignavan39 commented on services/smtp/.env.example
> +SENDER_PASSWORD_GMAIL = "pyuvwbfwumkkqrfd"
Надеюсь это не настоящий пароль, если настоящий срочно git reset git push -f

2022-07-08 17:38 UTC, enmex commented on services/smtp/.env.example
> +SENDER_GMAIL = "infbrokerinfo@gmail.com"
c envDefault не робит

2022-07-08 18:00 UTC, enmex commented
close #42

2022-07-09 05:17 UTC, ignavan39 requested changes

2022-07-09 05:17 UTC, ignavan39 commented on frontend/src/App.tsx
> +          <Route path="/invitations/{code}" element={<Invitation />} />
А это так не заработает

2022-07-09 05:17 UTC, ignavan39 commented on frontend/src/App.tsx
> +        <Invitation isInvitation={isInvitation} setOpen={invState}/>
Это не нужно потому что это на уровне роутера разрешится и чел сразу попадает в нужный компонент

2022-07-09 05:17 UTC, ignavan39 commented on frontend/src/App.tsx
> +          <Route path="/invitations/{code}" element={<Invitation />} />
Тут онли регулярка а в самом компоненте из location вытащи

2022-07-09 05:17 UTC, ignavan39 commented on frontend/src/state/Invitation.state.ts
> +    const cache = localStorage.getItem("invitation");
А зачем локал стор для него🤔🤔🤔🤔

2022-07-09 05:17 UTC, ignavan39 commented on frontend/src/App.tsx
> +          <Route path="/invitations/{code}" element={<Invitation />} />
window.location.href

2022-07-09 05:17 UTC, ignavan39 commented on frontend/src/state/Invitation.state.ts
> +const getDefaultInvitation = () => {
А зачем вообще для него свой Стейт 🤔

2022-07-09 05:17 UTC, ignavan39 commented on services/smtp/sender/services/sender.go
> +	// Here is the key, you need to call tls.Dial instead of smtp.Dial
Комменты удали

2022-07-09 05:17 UTC, ignavan39 commented on services/smtp/server.go
> +func NewAPIServer(listenOn string) *Server {
Не поправил

2022-07-09 06:18 UTC, ignavan39 commented on services/smtp/.env.example
> +SENDER_GMAIL = "infbrokerinfo@gmail.com"
Так я не про это в example оставь пустым

2022-07-09 06:18 UTC, ignavan39 commented on services/smtp/.env.example
> +SENDER_PASSWORD_GMAIL = "pyuvwbfwumkkqrfd"
Тогда наверное есть смысл переименовать поле ?)

2022-07-09 06:19 UTC, ignavan39 commented on services/smtp/.env.example
> +SENDER_PASSWORD_GMAIL = "pyuvwbfwumkkqrfd"
И это тож в example оставь пустым

2022-07-09 06:20 UTC, ignavan39 commented on frontend/src/pages/auth/Verification.tsx
> +import styled from "styled-components";
А что это за файл?

2022-07-09 06:24 UTC, ignavan39 commented on frontend/src/state/User.state.ts
>    key: "isLoggined",
Есть смысл ещё key поправить

2022-07-09 06:24 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    status: string,
Статус это enum же

2022-07-09 06:24 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    status: string,
Ну или Юнион сделай типа

```ts
status: 'first' | 'second' и тд

```

2022-07-09 06:24 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    systemStatus: string,
Аналогично

2022-07-11 06:43 UTC, enmex commented
close #45

2022-07-15 08:07 UTC, ignavan39 requested changes

2022-07-15 08:07 UTC, ignavan39 commented on frontend/src/state/User.state.ts
>    key: "isLoggined",
Не поправил

2022-07-15 08:07 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    status: string,
Не поправил

2022-07-15 08:07 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    systemStatus: string,
+

2022-07-15 08:07 UTC, ignavan39 commented on services/core/config/config.go
> +	ExternalHost string `env:"AMQP_EXTERNAL_HOST" envDefault:"localhost"`
Отформатировать

2022-07-15 08:07 UTC, ignavan39 commented on services/core/service/invitation/publisher/invitation_queue.go
> +	queueName := fmt.Sprintf(
UUID

2022-07-15 08:07 UTC, ignavan39 commented on services/core/service/invitation/publisher/publisher.go
> +	connections     map[string]*InvitationQueue
map[string] map [string] queue

2022-07-16 04:49 UTC, ignavan39 requested changes

2022-07-16 04:49 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +    status: string,
Сделай Юнион ты же знаешь какие статусы могут быть

2022-07-16 04:49 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +                console.log("Subscribed");
Доделай эту часть

2022-07-16 04:49 UTC, ignavan39 commented on frontend/src/components/invitation/Invitation.tsx
> +        console.log(response);
Это нужно?

2022-07-16 04:49 UTC, ignavan39 commented on frontend/src/pages/auth/Verification.tsx
> +      if (!state.code) {
А зачем исключение? Просто рисуй в компоненте что поле пустое добавь в HTML minLenght

2022-07-20 05:45 UTC, ignavan39 commented on frontend/src/components/invitation/Invitation.tsx
> +  const [connection, setConnection] = useState<{
Это тут не нужно

2022-07-20 05:45 UTC, ignavan39 commented on frontend/src/state/Invitation.state.ts
> +            status: null,
Да там тогда весь инвайт nullи тогда вообще нет смысла его в кэше хранить так как все равно бек по очереди оповестит

2022-07-20 05:45 UTC, ignavan39 commented on frontend/package.json
> +    "precompiled-mqtt": "^4.3.13",
А зачем?

2022-07-21 08:51 UTC, enmex commented on frontend/src/pages/auth/Verification.tsx
> +      if (!state.code) {
как это делается?

2022-07-21 09:20 UTC, enmex commented on frontend/src/pages/auth/Verification.tsx
> +      if (!state.code) {
А, понел

2022-07-21 18:06 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +    getData: async <T> (code: string, host: string, port: number | null, queueName: string): Promise<T | null> => {
Сделай тогда некий интерфейс под это потому что тут всегда один тип будет

2022-07-21 18:07 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +        const url = "http://" + host + ":" + port + "/ws";
Http не всегда будет, это корректно только для локальной разработки

2022-07-21 18:08 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +    getData: async <T> (code: string, host: string, port: number | null, queueName: string): Promise<T | null> => {
Хост и порт не должны передаваться сюда они должны храниться в сервисе

2022-07-21 18:08 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +                data = JSON.parse(decode(message.toLocaleString())) as T
Сюда вот нужно передать коллбек из аргументов

2022-07-21 18:08 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +        return Promise.resolve(data);
Либо асинхронные функции либо промисы но никак не вместе

2022-07-21 18:09 UTC, ignavan39 commented on frontend/src/api/Connection.ts
> +    getData: <T> (code: string, host: string, port: number | null, queueName: string) => Promise<T | null> | null;
Почему Т?

2022-07-21 18:09 UTC, ignavan39 commented on frontend/src/components/invitation/Invitation.tsx
> +        console.log("useEffect");
?

2022-07-21 18:10 UTC, ignavan39 commented on frontend/src/components/invitation/Invitation.tsx
> +                                                           response.consume.port,
С форматированием явные проблемы

2022-07-21 18:11 UTC, ignavan39 commented on frontend/src/pages/workspace/Workspaces.tsx
> +                                                      ? p.createdAt < n.createdAt
Отформатировать

2022-07-21 18:11 UTC, ignavan39 commented on frontend/src/state/Invitation.state.ts
> +    if (!cache) {
Вопрос все тот же

2022-07-21 18:11 UTC, ignavan39 commented on frontend/src/state/Invitation.state.ts
> +    }
Тут можно return в одну строку

2022-07-21 18:12 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    status: InvitationStatus | null,
Почему он может быть null?

2022-07-21 18:12 UTC, ignavan39 commented on frontend/src/types/Invitation.ts
> +    systemStatus: SystemStatus | null,
Тот же вопрос

2022-07-21 18:13 UTC, ignavan39 commented on frontend/src/types/Workspace.ts
> +    createdAt: Date | null;
Почему можно быть нулл?

2022-07-22 07:43 UTC, enmex commented on frontend/src/api/Connection.ts
> +        const mqtt = require('mqtt/dist/mqtt');
это вместо импорта, так почему-то работает

2022-07-22 09:41 UTC, ignavan39 approved these changes

2022-07-22 09:42 UTC, merged